### ISSUE TITLE
Invalid foreign key IDs

### ISSUE THREAD

**Issue by chescales** [sanoma/django-arctic#100]
In the list view, when I add one field to be a link to another method, it doesn't create the foreign key ids to the proper object, as it uses the ID of the listed object instead of the ID of the FK. For instance I have this code:

`field_links = {
        'id': 'user-pictures:update',
        'user__user_slug': 'sbusers:update',
    }
`

And for the sake of argument let's say that I have User Pictures with IDs 1 to 10, and all of them belong to Users with IDs 1 to 3.

This will result in a ListView of 10 items, 'id' will point to User Picture 1, 2, 3, 4, 5, etc., but the User Slug will point to the Users with IDs 1, 2, 3, 4, 5, etc., using the same PK as the User Picture, instead of pointing to the correct Users with IDs 1, 1, 1, 2, 2, 2, etc. (it may be a bit confusing to read, sorry about that!)

The Foreign Keys should take the correct user_id instead of the listed object's id.

**Comment by mmarcos** [comment]
@Silveron I think this has been solved with the urls field, can you confirm Ron?

**Comment by Silveron** [comment]
At the moment you can use the method get_urls to define which arguments should be used to handle named urls.

see arctic.generics.View.get_urls()

"        Used for resolving urls when displaying nested objects, see arctic_url.

        For example, generally you just have /foo/create as
        a url, but with nested, you may have: /foo/<id>/bar/create/ and <id>
        would be a parent id. These are then required to resolve urls.

        @returns
        {named_url, (url_param, url_param),}
        || {named_url, [url_param, url_param],}

        if you provide a list and in this list there are strings, it will try
        to get field of that item. This is especially useful for listviews with
        action_links and field_links.
"

So by placing the following code and you should be fine:

`    def get_urls(self):
        return {
            'user-pictures:update': ['pk'],
        }`

Please let me know if this comment helped you out.

**Comment by chescales** [comment]
@Silveron I tried this but still not working

```    
def get_urls(self):
    return {
        'sbusers:update': ['user_id'],
        'schools:update': ['related_school_id'],
    }
```

**Comment by chescales** [comment]
My field_links look like the following:

```
field_links = {
    'title': 'memories:update',
    'user__user_slug': 'sbusers:update',
    'related_school': 'schools:update',
}
```

**Comment by mmarcos** [comment]
I made some changes in url linking, try the following:

    field_links = {
        'title': 'memories:update',
        'user__user_slug': ('sbusers:update', 'user.pk'),
        'related_school': ('schools:update', 'related_school.pk'),
    }

**Comment by chescales** [comment]
After the latest changes I now get the correct 'related_school' foreign key, but the invalid 'user__user_slug' foreign key, with the code exactly as your example.

**Comment by mmarcos** [comment]
fixed in develop, get_urls() will be removed, the proper way to define alternative link keys is described in the field_links documentation:
http://django-arctic.readthedocs.io/en/develop/reference/#listview
