### ISSUE TITLE
Refactor tests to make use of django-pytest instead of only pytest.

### ISSUE THREAD

**Issue by Silveron** [sanoma/django-arctic#107]
Setup django db with:
@pytest.mark.django_db

And create and login users in fixtures.

Use the example project as testcase.

Instead of monkey patching urlresolver for the menu test for example.
Menu tests will be/is disabled now, these tests should work again with new setup. Also the other existing tests.

**Comment by mmarcos** [comment]
part of the cleanup of stale tickets, if needed a new one can be opened with concrete steps needed to solve it, and someone who's willing to do it
