### ISSUE TITLE
Cleanup the ListView template

### ISSUE THREAD

**Issue by mmarcos** [sanoma/django-arctic#111]
Currently the ListView template uses too much logic to display the data, it also assumes that data comes from a queryset. So the plan is to:
- remove all unneeded logic from the template
- treat all data as dictionaries/lists and no longer assume it comes from a queryset
- a column value can be either the display value, or a tuple/list with (id, display_value).
  This way the display value will be shown, and the id can be optionally used with a field link.

**Comment by andreyrusanov** [comment]
Btw it would be nice to split list view template on a few includes, to be able to customize table raw, or whole table, ot table cell with overriding specific template. Now for this customization whole list template should be copy pasted

**Comment by mmarcos** [comment]
Well you can use virtual fields to customise the contents of a cell, of field_classes to add a custom class to a cell, what other kinds of customisations would you like to do?

**Comment by andreyrusanov** [comment]
For instance custom CSS classes or any other layout related things

**Comment by mmarcos** [comment]
this ticket is fixed in develop, other ways to improve ListViews will come through additional tickets describing the concrete steps
