### ISSUE TITLE
Site becoming unresponsive on large datasets

### ISSUE THREAD

**Issue by chescales** [sanoma/django-arctic#134]
Hi there. I would like to open this ticket after a discussion with Miguel too, so we take the following into account.

At our project we have a data set of 5 million users, and some tables have more than that amount of records. Currently, only having migrated 200k users the site already times out (HTTP 504) when opening/creating a model instance with a foreign key with 200k options.

We should change the way the widgets work in order to be able to work with 200k, or millions of records, otherwise the site becomes unusable as it is right now for us.

Thanks for your effort!

**Comment by mmarcos** [comment]
fixed, added optional ajax based autocomplete for foreign keys
