### ISSUE TITLE
support for django 1.10

### ISSUE THREAD

**Issue by ddaan** [sanoma/django-arctic#164]
The current install doesn't work with django 1.10 as django-extra-views is lacking support for django 1.10 at the moment. 

We currently use a install from github/sanoma/django-extra-views, however because django arctic has still django-extra-views 0.7.1 as requirement our deployment process overwrites it.

**Comment by mmarcos** [comment]
The current master branch of django-extra-views supports Django 1.10, so we can pin the current master on the requirements until a proper version is released on PyPI

**Comment by ddaan** [comment]
check, but bear in mind that setup.py currently reads requirements/base.txt for it requirements. setup.py doesn't allow pinning of commits like we use to do in requirement files (It need to be in dependency_links).

**Comment by mmarcos** [comment]
django-extra-views was upgraded to 0.9.0 which has full Django 1.10 compatibility, requirements file in arctic have been updated to reflect this version
