### ISSUE TITLE
add default value for paginate_by in listview

### ISSUE THREAD

**Issue by ddaan** [sanoma/django-arctic#188]
It would be nice if there was one central place to define the number of items on one page in the list view. 

pro:
- uniformity in the application, same amount of items on one page.
- no more accidental full table dumps in production.

con:
- better to be explicit than implicit. 

I suggest to add a settings DEFAULT_PAGINATE_BY

**Comment by mmarcos** [comment]
we'll leave it like this until more complaints come about this issue, this is the standard Django ListView behaviour
