### ISSUE TITLE
LOGIN_URL and LOGOUT_URL has to be set even if no authentication used

### ISSUE THREAD

**Issue by andreyrusanov** [sanoma/django-arctic#199]
It is not a comon case for CMS, but still is possible(and I just faced such situation :) ) that app is not supposed to use authentication. However, LOGIN_URL and LOGOUT_URL has to be set. Of course, it is possible to set them to home url, but it smells like a hack. 

So let's allow them to be None?

**Comment by mmarcos** [comment]
fixed in develop branch
