### ISSUE TITLE
Make inlines more dynamic by introducing JS magic

### ISSUE THREAD

**Issue by andreyrusanov** [sanoma/django-arctic#201]
It would be nice to be able to add and remove formsets dynamically using only JS... And have this feature out of the box!

**Comment by mmarcos** [comment]
This is a useful code snippet for replicating forms with javascript:
http://jsfiddle.net/XpAk5/

**Comment by andreyrusanov** [comment]
Useful example of dealing with cloning Selectize(not a rocket science, actually)
https://mariolurig.com/coding/selectize-js-combobox-cloning-destroying/

**Comment by andreyrusanov** [comment]
Another thought about this issue - maybe we can make it as a standlone JS library? I think it is good idea to another opensource project.
