### ISSUE TITLE
Create float labels bootstrap 4

### ISSUE THREAD

**Issue by BartvdWaerden** [sanoma/django-arctic#221]
Shopify example:
https://shop.smashingmagazine.com/6824959/checkouts/dd11a79b4ff584322218e86bbcfbce58

Bootstrap implementation that can easily be visually tweaked:
https://github.com/tonystar/bootstrap-float-label

**Comment by mmarcos** [comment]
Current issues:
- [] Float labels should only be applied in forms with the class `float-label`
- [] Text area should keep its original height and should be able to grow
- [] multi drop down should also be able to grow as more tags are added and need more lines.

**Comment by BartvdWaerden** [comment]
- [ ] Always show custom visual dropdown (same selctize as normal default dropdown)
- [ ] Multiselectize same height (45px) with one row, so smaller items
- [ ] Checkbox align center in form-group
- [ ] Textarea float-label (doesn't do animation, is already in end state)

**Comment by mmarcos** [comment]
fixed and merged in develop
