### ISSUE TITLE
ListView pass raw data into filtering query

### ISSUE THREAD

**Issue by wolendranh** [sanoma/django-arctic#242]
As you can see from code  `arctic.generics.ListView.get_object_list` view provide searching/filtering functionality. In both cases for `SimpleSearchForm` and user defined `advanced_search_form` no data validation is being done. 

Also in case of user defined `advanced_search_form` and `get_search_filter` method on form itself  you are not able to access `self.cleaned_data` as no prior `is_valid` method call was done. 

I think that we have to clean data at some point in Arctic, as raw data in queries and widgets  will result in late errors and confusion.

**Comment by Gooliver2** [comment]
Fixes regarding validation of search forms and displaying errors to user are in [https://github.com/sanoma/django-arctic/pull/246](url)
