### ISSUE TITLE
Simple search form 'search' button markup broken

### ISSUE THREAD

**Issue by wolendranh** [sanoma/django-arctic#250]
![button1](https://user-images.githubusercontent.com/6746231/35743101-2b3f0edc-0845-11e8-963e-21bc6dffe2d9.png)
Looks like 
django-arctic/arctic/templates/arctic/partials/base_data_table.html search div is the issue.
`<div class="input-group-addon" js-search-submit><i class="fa fa-search"></i></div>`
Element is being rendered as displayed on picture, which makes whole form look broken.

**Comment by Gooliver2** [comment]
Same for Advanced search button. Fixed in https://github.com/sanoma/django-arctic/pull/256
