### ISSUE TITLE
Add support of `initial` data for SelectizeAutoComplete

### ISSUE THREAD

**Issue by wolendranh** [sanoma/django-arctic#303]
Currently `SelectizeAutoComplete` widget does not support pre fill of initial value. 

Use case:

1. User types some string into input generated by widget
2. Form is being saved 
3. User open `Details/Update` page with previously saved object
4. widget powered field is not able to show previously selected/typed data

**Comment by mmarcos** [comment]
i cannot replicate this issue, can you give some more information about this

**Comment by mmarcos** [comment]
Issue is with ChoiceField, not when ModelChoiceField is used
