### ISSUE TITLE
Can not use TemplateView to overide handler404

### ISSUE THREAD

**Issue by aodarc** [sanoma/django-arctic#336]
When I want to create custom 404 page I'm trying to use TemplateView to render regular page.
But when we have unknown url Arctic trying to get namespase and url-name from resolver_match but it's None.
[The problem is there](https://github.com/sanoma/django-arctic/blob/develop/arctic/utils.py#L57)

**Comment by mmarcos** [comment]
Can you perhaps do a pull request on this one with the fix?
