### ISSUE TITLE
Keep sidebar menu open on more urls

### ISSUE THREAD

**Issue by David-Esteves** [sanoma/django-arctic#349]
Currently the sidebar menu stays open if the user is in a child url of that section, but that stops happening as soon as the user moves away from those links.

Arctic already allows more links to be passed to keep the sidebar open
e.g.
```
(_('Articles'), 'articles:list', 'fa-newspaper-o', (
        (_('Articles overview'), 'articles:list', (
            'articles:feed-list',
            'articles:pending-list',
            'articles:create',
            'articles:position',
        )),
    )),
```
After this issue is fixed this would also be possible
```
e.g.
(_('Articles'), 'articles:list', 'fa-newspaper-o', (
        (_('Articles overview'), 'articles:list', (
            'articles:*',
        )),
    )),
```
This would keep the sidebar articles-list open if the url is part of articles:*

**Comment by mmarcos** [comment]
The syntax should be more like this:

    ARTIC_MENU =(
    (_('parent'), None, 'fa-download', (
            (_('child 1'), 'site:app:view1'),
            (_('child 2'),  'site:app:view2'),
            # keep menu section opened if the bellow urls also match, 
            # when clicked the first item will be displayed
            (_('child 3'),  ('site:app:view3', 'site:app:create-view1', 'site:app:create-view2')),
        )),
    )
