### ISSUE TITLE
Choices field proper display in the ListView

### ISSUE THREAD

**Issue by chescales** [sanoma/django-arctic#79]
When displaying a `choices` field in the ListView, it shows the actual value instead of the display, which is preferred in the CMS environment. Setting it to the field name `memory_type` displays this:

![screen shot 2016-10-05 at 10 41 05](https://cloud.githubusercontent.com/assets/3706329/19106550/3c1001a2-8ae8-11e6-8b67-1c124739a138.png)

While if you put the actual helper method that gets added automatically, `get_memory_type_display`, it displays correctly the content, but displays an invalid title then:

![screen shot 2016-10-05 at 10 42 30](https://cloud.githubusercontent.com/assets/3706329/19106584/7008cdc2-8ae8-11e6-8ab2-7e1f1fc5a856.png)

It would be nice that before displaying the column, there would be a check trying to find a "get_XXX_display" in the instance, and if it's there, show that value instead of the field's value.

**Comment by mmarcos** [comment]
Instead of giving the field as a string in the `fields` list you can also give a (title, field) tuple so in this case you could do fields = [('get_memory_type_display', 'Memory Type')].
Another option is to give a verbose property to the model field, if given, this verbose name will be used instead of the field name.

**Comment by MaartenPI** [comment]
Doesn't Marcos' solution help? [('get_memory_type_display', 'memory type')] That would solve your problem.

Or is it about automating this step, so you don't have to look up the field name in the model? If that's the case, it seems easier to just stick to Django convention. ChoiceFields aren't used all over the place anyway.

**Comment by mmarcos** [comment]
well the solution I mentioned fixes it, but get_{field}_display should have worked implicitly in this case,
the fallback sequence should be: first try get_{field}_display, if not available then use the field value.
