### ISSUE TITLE
Capitalise the Columns of the ListView

### ISSUE THREAD

**Issue by chescales** [sanoma/django-arctic#80]
This is a very small issue, but it would be nice to see the column titles start with a capital letter also for the field columns. Currently only the _Actions_ column has this behaviour.

![screen shot 2016-10-05 at 10 46 15](https://cloud.githubusercontent.com/assets/3706329/19106729/3eb3715e-8ae9-11e6-8639-86f77e3716a7.png)

**Comment by mmarcos** [comment]
That's a nice addition. 
By the way you can always have a custom title by adding a verbose property to the model field.

**Comment by mmarcos** [comment]
fixed and merged in develop
