### ISSUE TITLE
Create modular blocks to use in layouts and articles.

### ISSUE THREAD

**Issue by daan944** [sanoma/django-arctic#89]
Most sites nowadays need snippets of variable data-structure for cross platform compatibilty and a better user-experience. A snippet will be parsed by an app (website or phone app) and behavior is dependent of implementation.

You could use these snippets to display: 
- Video
- Slideshow
- Questionnaire / form
  In articles or layouts.

These snippets, we call them 'blocks', need context for proper functioning. E.g. a videoblock needs to know what video to display. Since all sites need to build their own blocks, we need a model and form that is highly customizable, syncs with JS and can support all kinds of context.

Acceptance criteria:
1. Is context stored in JSON? yes
2. Is a block easily added by a developer? yes
3. Is there need to add a template/form by the developer? no
4. If desired, can the template be customized by the developer? yes
5. Is this block validated by the backend before saving? yes

@bartee and I already started work on it.

**Comment by mmarcos** [comment]
part of the cleanup of stale tickets, if needed a new one can be opened with concrete steps needed to solve it, and someone who's willing to do it
