### ISSUE TITLE
Settings missing model defaults after Swappable models introduced

### ISSUE THREAD

**Issue by chescales** [sanoma/django-arctic#99]
The following commit broke my running admin a few days ago:

https://github.com/sanoma/django-arctic/commit/4b585a6b571b19e2c189b7c115b43f26bf505862

In here the role models allowed overriding the default model, but the line `role = models.ForeignKey(settings.ARCTIC_ROLE_MODEL)` breaks compatibility with existing running platforms that didn't define that setting variable.

Both ARCTIC_ROLE_MODEL and ARCTIC_USER_ROLE_MODEL should have proper default values for backwards compatibility, and also because users who don't want to swap the model don't need to define the default value.

**Comment by mmarcos** [comment]
fixed in develop branch
